version: 3
endpoint: http://localhost:8080
admin_secret: jGLmIQ3g0KZ5FfUWVVXMMxzJKdjCmJU75afTXwdJcNGus0WDU3DegwSZ9egpeSuN
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
